plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

packageExtensions:
  # "@bhch/react-json-form@*":
  #   dependencies:
  #     "react-modal": "*"
  uniforms@*:
    dependencies:
      "react": "*"
  "@crxjs/vite-plugin@*":
    dependencies:
      vite: "*"
  # "@rjsf/chakra-ui@*":
  #   dependencies:
  #     "@chakra-ui/react": "*"
  #     "@chakra-ui/icons": "*"
  #     "chakra-react-select": "*"
  #     "@emotion/react": "*"
  #     "@emotion/cache": "*"
  #     "@emotion/weak-memoize": "*"
  # chakra-react-select@*:
  #   dependencies:
  #     "@chakra-ui/menu": "*"
  #     "@chakra-ui/spinner": "*"
  #     "@chakra-ui/media-query": "*"
  #     "@chakra-ui/system": "*"
  #     "@chakra-ui/form-control": "*"
  #     "@chakra-ui/layout": "*"
  #     "@chakra-ui/icon": "*"
  # react-select@*:
  #   dependencies:
  #     react-dom: "*"
  # "@chakra-ui/toast@*":
  #   dependencies:
  #     framer-motion: "*"
  # "@chakra-ui/transition@*":
  #   dependencies:
  #     framer-motion: "*"
  # "@chakra-ui/modal@*":
  #   dependencies:
  #     framer-motion: "*"
  # "@chakra-ui/popover@*":
  #   dependencies:
  #     framer-motion: "*"
  # "@chakra-ui/portal@*":
  #   dependencies:
  #     react-dom: "*"
  # "@chakra-ui/menu@*":
  #   dependencies:
  #     framer-motion: "*"
  # "@chakra-ui/tooltip@*":
  #   dependencies:
  #     framer-motion: "*"
  # "@chakra-ui/system@*":
  #   dependencies:
  #     "@emotion/styled": "*"
  #     "@emotion/react": "*"
  # "@chakra-ui/icon@*":
  #   dependencies:
  #     "@chakra-ui/system": "*"
  # "@emotion/styled@*":
  #   dependencies:
  #     "@emotion/react": "*"
  # "@chakra-ui/css-reset@*":
  #   dependencies:
  #     "@emotion/react": "*"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
